### ISSUE TITLE
I would really love a windows version of this program.

### ISSUE THREAD

**Issue by sanxofon** [xasopheno/weresocool#759]
Hello! In your README you state that if someone is "interested in using this software on Windows...", well I am. May be I can help testing, translating or something like that.

I'm just another cheap third world windows musician that uses MuseScore and plays microtonal music but can't do both, who would greatly benefit from your work if it could run on windows pc. I really love and appreciate what you're doing. Great Job!

I think this could be an Issue that can be eventually be resolved and more people could give their thoughts on this thread, but may be it was inappropriate.

**Comment by psychedel** [comment]
If you have Windows 11 - you can try WSL to run it for now.
https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by xasopheno** [comment]
Great to hear from you! In the short term, you can play with the language in the browser here on Firefox and Chrome:
https://www.weresocool.org/

Are you a programmer as well? 
Thanks,
Danny

**Comment by xasopheno** [comment]
***Update*** After some fiddling, I was able to get this running on Windows. I still have some cleanup to do, but I'll continue poking at this until I have a windows version for you to try.

**Comment by xasopheno** [comment]
_Update_: I have a PR up to add Windows support. 
https://github.com/xasopheno/weresocool/pull/762

**Comment by xasopheno** [comment]
_Cool Update_: PR is merged. WereSoCool runs on Windows! @sanxofon - If you give it a shot, please let me know how it goes.
